name: mmsn
description: "Mewad Maheshwari Samaj Nadiad Flutter Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  collection: ^1.19.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  pdfx: ^2.9.2
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  fluttertoast: ^9.0.0
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  flutter_keyboard_visibility: ^6.0.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/carouselImages1.jpeg
    - assets/carouselImages2.jpeg
    - assets/carouselImages3.jpeg
    - assets/carouselImages4.jpeg
    - assets/profileImageHead1.jpeg
    - assets/profileImageHead1Wife.jpeg
    - assets/profileImageHead1Son.jpeg
    - assets/profileImageHead1Daughter.jpeg

  